feature/compatility-110
pocky/SyliusBannerPlugin pull request #1
Opened 2021-07-30 10:37 UTC by Stolidbug

upgrade of the plugin in the new architecture

2021-07-31 19:40 UTC, pocky requested changes
You need to update your PR according to this one : https://github.com/pocky/SyliusCookieAlertPlugin/pull/3/files

- Remove old files, add new ones.
- PHP files must have a blank line at the end.
- Change the commit message to "Update plugin compatibility to 1.10"

2021-07-31 19:40 UTC, pocky commented on .gitignore
> +/etc/build/.gitignore
Remove this change

2021-07-31 19:40 UTC, pocky commented on composer.json
>          ]
Inline this array

2021-07-31 19:40 UTC, pocky commented on docs/CONTRIBUTING.md
> +When you open a Pull Request, you agree to license your code under the [EUPL-1.2](../../../../LICENSE) and to transfer the copyright on the submitted code to the owner of this project.
Invalid path for LICENSE file

2021-07-31 19:50 UTC, Stolidbug commented on docs/CONTRIBUTING.md
> +When you open a Pull Request, you agree to license your code under the [EUPL-1.2](../../../../LICENSE) and to transfer the copyright on the submitted code to the owner of this project.
I had noticed it when I sent my RP it was done afterwards

2021-08-02 07:26 UTC, Stolidbug commented on .gitignore
> +/etc/build/.gitignore
check

2021-08-02 07:26 UTC, Stolidbug commented on composer.json
>          ]
check

2021-08-02 21:56 UTC, pocky requested changes
- Remove old unused files
- Update tests files

2021-08-02 21:56 UTC, pocky commented on src/EventListener/SlidesUploadListener.php
> +
Remove this line

2021-08-02 21:56 UTC, pocky commented on src/Repository/BannerRepository.php
> +
Remove this line

2021-08-03 08:56 UTC, Stolidbug commented on src/EventListener/SlidesUploadListener.php
> +
check

2021-08-03 08:56 UTC, Stolidbug commented on src/Repository/BannerRepository.php
> +
check

2021-08-03 13:26 UTC, pocky requested changes

2021-08-03 13:26 UTC, pocky commented on src/EventListener/SlidesUploadListener.php
> +}
Missing EOF

2021-08-03 13:26 UTC, pocky commented on src/Repository/BannerRepository.php
> +}
Missing EOF

2021-08-03 13:26 UTC, pocky commented on tests/Application/config/sylius/1.10/bundles.php
> +];
Missing EOF

2021-08-03 13:26 UTC, pocky commented on tests/Application/config/sylius/1.10/packages/prod/jms_serializer.yaml
> +        - JSON_PRESERVE_ZERO_FRACTION
Missing EOF

2021-08-03 13:26 UTC, pocky commented on tests/Application/config/sylius/1.9/bundles.php
> +];
Missing EOF

2021-08-03 13:26 UTC, pocky commented on tests/Application/config/routes.yaml
> -    prefix: /admin
You must add your routes (according to the installation guide) like your configuration file in config path.

2021-08-03 13:58 UTC, Stolidbug commented
check

2021-08-05 11:29 UTC, merged